#!/bin/sh

#Works in gnome-terminal
#stop cluster for a new execution
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/stop-cluster.sh"


sleep 3
#start cluster for a new execution
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/start-cluster.sh;exec bash"


sleep 3
#Start CSV_Parser for read from Bosnia2.csv and write in topic input-topic-job1
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c utils.CSV_Parser /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -csv-path /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/MyDocs/openaq_Bosnia2.csv -topic input-topic-job1 -p 4;exec bash"


sleep 20
#Start FirstAlgorithmPass for Bosnia2 csv with keys=location and aggr=value , write in topic output-topic-job1
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c tuc.FirstAlgorithmPass /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -all-attributes location,city,country,utc,local,parameter,value,unit,latitude,longitude,attribution -keys location -aggr value -p 4;exec bash"


# sleep 40
# #Start SecondAlgorithmPass,write in topic output-topic-job1
# gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c tuc.SecondAlgorithmPass /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -p 4;exec bash"
