#!/bin/sh

#Works in gnome-terminal
#stop cluster for a new execution
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/stop-cluster.sh"

gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/zookeeper-server-start.sh /home/skalogerakis/kafka_2.12-2.4.0/config/zookeeper.properties;exec bash"

sleep 2

gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-server-start.sh /home/skalogerakis/kafka_2.12-2.4.0/config/server.properties;exec bash"

sleep 3
#start cluster for a new execution
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/start-cluster.sh;exec bash"

#sleep 10

#NOT OBLIGATORY TO CREATE NEW
#Create new topic with name csvtokafka in localhost:9092
#gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic input-topic-job1;exec bash"


sleep 3
#Start CSV_Parser for read from Bosnia2.csv and write in topic input-topic-job1
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c utils.CSV_Parser /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -csv-path /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/MyDocs/population.csv -topic input-topic-job1 -p 4;exec bash"


sleep 20
#Start FirstAlgorithmPass for Bosnia2 csv with keys=location and aggr=value , write in topic output-topic-job1
gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c tuc.FirstAlgorithmPass /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -all-attributes Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number -keys District.Name,District.Code -aggr Number -p 4 -windows-time 60;exec bash"


# sleep 40
# #Start SecondAlgorithmPass,write in topic output-topic-job1
# gnome-terminal -- bash -c "/home/skalogerakis/flink-1.9.2-bin-scala_2.12/flink-1.9.2/bin/flink run -c tuc.SecondAlgorithmPass /home/skalogerakis/TUC_Projects/TUC_Advanced_Database_Systems/ECE622/target/ECE622-1.0-SNAPSHOT.jar -p 4 -windows-time 60;exec bash"
